name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NATS_CLIENT_LOG: 1
      NATS_TEST_LOG: 1
    strategy:
      fail-fast: false
      matrix:
        nats: ['2.10', '2.11','2.12', 'latest']
        php: ['8.1', '8.2', '8.3', '8.4', '8.5']
        verbose: ['0', '1']
    steps:
      - uses: actions/checkout@v2
        # This action does not use the php-version from setup-php, so we need to
        # specify it here as well or do not use it at all and run composer install manually.
        # Without this instantiator triggers an error of string const.
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          php_extensions: curl zip xml dom mbstring
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: docker compose up -d
        working-directory: docker
        env:
          NATS_IMAGE_TAG: ${{ matrix.nats }}
      - run: vendor/bin/phpunit --testsuite Tests
        env:
          NATS_CLIENT_VERBOSE: ${{ matrix.verbose }}
      - name: Coverage text report
        run: cat coverage/report.txt
      # - name: Coveralls
      #   if: matrix.php == '8.4' && matrix.verbose == '1'
      #   uses: coverallsapp/github-action@v2
      #   with:
      #     files: coverage/report.clover
